/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  Overrides,
  BigNumberish,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ChildContract, ChildContractInterface } from "../ChildContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_data",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "childAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "data",
        type: "uint256",
      },
    ],
    name: "ChildUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "index",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isEnabled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_data",
        type: "uint256",
      },
    ],
    name: "updateChild",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161033d38038061033d83398181016040528101906100329190610076565b8160008190555060018060006101000a81548160ff0219169083151502179055508060028190555050506100d3565b600081519050610070816100bc565b92915050565b6000806040838503121561008957600080fd5b600061009785828601610061565b92505060206100a885828601610061565b9150509250929050565b6000819050919050565b6100c5816100b2565b81146100d057600080fd5b50565b61025b806100e26000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80632986c0e51461004657806359569832146100645780636aa633b614610080575b600080fd5b61004e61009e565b60405161005b91906101ab565b60405180910390f35b61007e60048036038101906100799190610111565b6100a4565b005b6100886100e9565b6040516100959190610190565b60405180910390f35b60025481565b806000819055507f77327389b3dcb88eaa59a8747adfb8cdac2b3f77798e4ae51e77140ae20da233306000546040516100de929190610167565b60405180910390a150565b600160009054906101000a900460ff1681565b60008135905061010b8161020e565b92915050565b60006020828403121561012357600080fd5b6000610131848285016100fc565b91505092915050565b610143816101c6565b82525050565b610152816101d8565b82525050565b61016181610204565b82525050565b600060408201905061017c600083018561013a565b6101896020830184610158565b9392505050565b60006020820190506101a56000830184610149565b92915050565b60006020820190506101c06000830184610158565b92915050565b60006101d1826101e4565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b61021781610204565b811461022257600080fd5b5056fea2646970667358221220c413d243b83f362d28cfd6dd90443bf282131be6541f88c9d6ad331ae4f2fbac64736f6c63430008000033";

type ChildContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ChildContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ChildContract__factory extends ContractFactory {
  constructor(...args: ChildContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    _data: BigNumberish,
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ChildContract> {
    return super.deploy(
      _data,
      _index,
      overrides || {}
    ) as Promise<ChildContract>;
  }
  getDeployTransaction(
    _data: BigNumberish,
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_data, _index, overrides || {});
  }
  attach(address: string): ChildContract {
    return super.attach(address) as ChildContract;
  }
  connect(signer: Signer): ChildContract__factory {
    return super.connect(signer) as ChildContract__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ChildContractInterface {
    return new utils.Interface(_abi) as ChildContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChildContract {
    return new Contract(address, _abi, signerOrProvider) as ChildContract;
  }
}
